repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 01a675ea018f2fb714478a5ffb83fcea8374bb06 # v0.15.21 # pragma: allowlist secret
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml
      - id: ruff-format
        args:
          - --config=pyproject.toml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: a4d5d37e66ebcd6b3705204a1d6dbb56dea66338 # 0.49.0 # pragma: allowlist secret
    hooks:
      - id: markdownlint-fix
        args: [--dot, --disable=MD013, --disable=MD033]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: a30f0d816e5062a67d87c8de753cfe499672b959 # v1.5.5 # pragma: allowlist secret
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/pappasam/toml-sort
    rev: 2970ae9bb7124fe5117a27e10c10d2da051ce05a # v0.24.4 # pragma: allowlist secret
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 0cbe8f6e54466b1b48f9d41f44abb4d06c061b5e # v2.2.0 # pragma: allowlist secret
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml, --ignore-missing-imports]
        additional_dependencies:
          [pytest, pydantic, types-cachetools, types-toml]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4 # v3.1.0 # pragma: allowlist secret
    hooks:
      - id: prettier
        args:
          - --quote-props=as-needed
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0 # pragma: allowlist secret
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/Yelp/detect-secrets
    rev: 01886c8a910c64595c47f186ca1ffc0b77fa5458 # v1.5.0 # pragma: allowlist secret
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: .env.example
