[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=45", "wheel"]

[dependency-groups]
dev = [
    "msal>=1.34.0",
]
test = [
    "fastapi[standard]>=0.115.14",
    "pytest-httpx>=0.35.0",
]

[project]
authors = [
    {email = "h.moss@ucl.ac.uk", name = "Harry Moss"},
    {email = "n.loynes@ucl.ac.uk", name = "Nik Loynes"},
]
dependencies = [
    "aiohttp>=3.13.0",
    "cyclopts>=4.4.0",
    "defusedxml>=0.7.1",
    "destiny-sdk >=0.4.0,<0.5.0",
    "habanero>=2.3.0",
    "httpx>=0.28.0,<0.29.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.7.1,<3",
    "pydantic[email]>=2.0,<3.0",
    "toml>=0.10.2",
]
description = "Robot for adding full-text and other more fully featured enhancements to items in the destiny repo from alternate sources."
name = "fetch-everything-robot"
readme = "README.md"
requires-python = ">=3.13"
version = "0.2.0"

[project.optional-dependencies]
dev = [
    "detect-secrets>=1.5.0",
    "mypy>=1.18.2",
    "pre-commit>=4.0.1",
    "pytest-httpx>=0.35.0",
    "pytest>=8.3.4",
    "ruff>=0.8.6",
]
docs = [
    "mkdocs",
    "mkdocs-include-markdown-plugin",
    "mkdocs-material",
    "mkdocs-mermaid2-plugin>=1.2.1",
    "mkdocstrings",
    "mkdocstrings-python",
    "tox>=4.27.0",
]
test = [
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
]

[project.scripts]
fetch-everything = "fer.local.run:app"

[tool.mypy]
explicit_package_bases = true
plugins = ["pydantic.mypy"]

[tool.pytest.ini_options]
addopts = ["--color=yes", "--import-mode=importlib", "--verbose"]
pythonpath = "."
testpaths = ["tests"]

[tool.ruff]
extend-exclude = ["docs/*.py", "fer/migrations/versions/*.py"]
fix = true
force-exclude = true
target-version = "py313"
lint.ignore = [
    "COM812", # trailing commas (ruff-format recommended)
    "D203", # no-blank-line-before-class
    "D205", # missing-blank-line-after-summary
    "D212", # multi-line-summary-first-line
    "D403", # forcing upper-case - feel free to change @harry
    "D407", # removed dashes lines under sections
    "D417", # argument description in docstring (unreliable)
    "ERA001", # commented-out code - REMOVE THIS OVERRIDE ASAP
    "FIX002", # implicit trust that TODOs are not trivial, or else they would be fixed
    "ISC001", # simplify implicit str concatenation (ruff-format recommended)
]
lint.per-file-ignores = {"fer/enhancement_processor.py" = [
    "PLR0913", # Too many arguments in function definition
], "fer/fetch_fulltext.py" = [
    "PLR0915", # Too many statements
], "fer/fetching/unpaywall.py" = [
    "PLR0915", # Too many statements
], "fer/main.py" = [
    "S104", # Possible binding to all interfaces
], "scripts*" = [
    "ANN201", # Missing return type annotation for public function
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public module
    "D103", # Missing docstring in public function
    "D401", # First line of docstring should be in imperative mood
    "E501", # Line too long
    "ERA001", # Found commented-out code
    "F841", # Local variable name is assigned to but never used
    "RET504", # Unnecessary assignement to variable before return statement
    "TRY300", # Consider moving this statement to an else block
], "tests*" = [
    "ANN001", # No return type annotation
    "ANN201", # No return type annotation
    "ARG001", # Unused function argument
    "D100", # Missing docstring in public module
    "D103", # Missing docstring in public function
    "E501", # Line too long
    "INP001", # File is part of an implicit namespace package.
    "PLR0913", # Too many arguments in function definition
    "PLR2004", # Magic value used in comparison
    "S101", # Use of `assert` detected,
    "SLF001", # calling private methods directly
]}
lint.select = ["ALL"]
lint.mccabe.max-complexity = 18
lint.pep8-naming.classmethod-decorators = ["classmethod"]

[tool.setuptools]
package-dir = {"" = "."}
packages = ["fer"]

[tool.tomlsort]
all = true
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
overrides."project.classifiers".inline_arrays = false
overrides."tool.coverage.paths.source".inline_arrays = false
overrides."tool.tox.env.docs.commands".inline_arrays = false

[tool.tox]
env_list = [
    "py313",
]

[tool.tox.env.docs]
commands = [
    [
        "mkdocs",
        "build",
        "--strict",
    ],
]
extras = [
    "docs",
]
gh.python."3.13" = ["py313"]
